adminUser: admin
adminPassword: admin

service:
  type: NodePort
  nodePort: 30030

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

grafana.ini:
  server:
    root_url: http://localhost:30030
  users:
    allow_sign_up: false
  auth.anonymous:
    enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki-gateway.logging.svc.cluster.local
        isDefault: true
        editable: false

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folderAnnotation: grafana_folder
    provider:
      foldersFromFilesStructure: true
