apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Allocates 5 Gigabytes of persistent spacea43q242  q11`  