apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
