apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.storage.size }}
  {{- if .Values.mariadb.storage.storageClass }}
  storageClassName: {{ .Values.mariadb.storage.storageClass | quote }}
  {{- end }}
